FROM nginx:1.21.6
COPY /build /usr/share/nginx/html
COPY /build/lobstr/index.html /usr/share/nginx/html/lobstr.html
COPY /subdomains/ /usr/share/nginx/html/subdomains/
COPY /version.htm /usr/share/nginx/html
COPY /devnginx.conf /etc/nginx/nginx.conf
COPY /.htpasswd /etc/nginx
COPY /devweb.default.conf /etc/nginx/conf.d/default.conf
COPY /devlobstr.conf /etc/nginx/conf.d/lobstr.conf
COPY /devapp.conf /etc/nginx/conf.d/devapp.conf
